return Def.ActorFrame{
	LoadActor(THEME:GetPathG("ScreenOptions","more/_triangle"))..{
		--effectdelay,.6;
		InitCommand=cmd(blend,Blend.Add;x,-38;diffuseblink;effectcolor1,color("0.6,0.6,0.6,1");effectperiod,0.4;effectoffset,0.2;effectclock,"beat");
		ExitSelectedP1Command=cmd(stoptweening;linear,.15;rotationz,-90);
		ExitUnselectedP1Command=cmd(stoptweening;linear,.15;rotationz,0);
	};
	LoadActor(THEME:GetPathG("ScreenOptions","more/_triangle"))..{
		--effectdelay,.6;
		InitCommand=cmd(blend,Blend.Add;x,38;diffuseblink;effectcolor1,color("0.6,0.6,0.6,1");effectperiod,0.4;effectoffset,0.2;effectclock,"beat");
		ExitSelectedP2Command=cmd(stoptweening;linear,.15;rotationz,90);
		ExitUnselectedP2Command=cmd(stoptweening;linear,.15;rotationz,0);
	};
	LoadActor(THEME:GetPathG("ScreenOptions","more/moreexit"))..{
		InitCommand=cmd(y,-19;croptop,.57;cropbottom,.1);
		GainFocusCommand=cmd(stoptweening;linear,.15;y,-16;croptop,.57;cropbottom,.1);
		LoseFocusCommand=cmd(stoptweening;linear,.15;y,16;croptop,.07;cropbottom,.6);
	};
};