return Def.ActorFrame{
	InitCommand=cmd(fov,52.4);
	Def.ActorFrame{
		InitCommand=cmd(x,SCREEN_CENTER_X+10;y,SCREEN_CENTER_Y+130;spin;effectmagnitude,60,0,0;);
		LoadActor(THEME:GetPathG("_memory","card"))..{
			OnCommand=cmd(zoom,1.1;linear,4.9;accelerate,.25;addx,75;decelerate,.25;addx,75;sleep,4.8;accelerate,.25;addx,-75;decelerate,.25;addx,-75;);
			OffCommand=cmd(stoptweening;accelerate,0.5;addx,-SCREEN_WIDTH*1.5);
		};
		Def.Quad{ InitCommand=cmd(clearzbuffer,true;zoom,0); };
	};
	LoadActor(THEME:GetPathB("","lolhi"))..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-80;fadeleft,0.3;faderight,0.3;cropleft,1.3;cropright,-0.3;zoom,0.3;);
		OnCommand=cmd(linear,1;cropleft,-0.3;zoom,2;linear,15;zoom,1.2;);
		OffCommand=cmd(stoptweening;linear,0.5;cropright,1.3;zoom,0.5);
	};

	LoadActor("usecard")..{
		InitCommand=cmd(x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y-80;zoom,0.91;diffusealpha,0;);
		OnCommand=cmd(sleep,1.50;linear,.4;diffusealpha,1;zoom,.9;linear,2.9;zoom,0.83;sleep,0;linear,0.2;diffusealpha,0;zoom,.8;);
		OffCommand=cmd(stoptweening;accelerate,0.5;addx,SCREEN_WIDTH*1.5);
	};
	LoadActor("achie")..{
		InitCommand=cmd(x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y-80;zoom,0.91;diffusealpha,0;);
		OnCommand=cmd(sleep,4.7;linear,.4;diffusealpha,1;zoom,.9;linear,3.9;zoom,0.83;sleep,0;linear,0.2;diffusealpha,0;zoom,.8;);
		OffCommand=cmd(stoptweening;accelerate,0.5;addx,SCREEN_WIDTH*1.5);
	};
	LoadActor("groovestats")..{
		InitCommand=cmd(x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y-80;zoom,0.91;diffusealpha,0;);
		OnCommand=cmd(sleep,8.9;linear,.4;diffusealpha,1;zoom,.9;linear,2.9;zoom,0.83;sleep,0;accelerate,0.5;addx,SCREEN_WIDTH*1.5);
		OffCommand=cmd(stoptweening;accelerate,0.5;addx,SCREEN_WIDTH*1.5);
	};

	LoadActor("usb icon")..{
		InitCommand=cmd(x,SCREEN_CENTER_X+500;y,SCREEN_CENTER_Y-80;glow,color("1,1,1,1"););
		OnCommand=cmd(sleep,1.0;decelerate,0.5;x,SCREEN_CENTER_X-220;glowshift;effectclock,"beat";effectoffset,1;effectperiod,2;sleep,10.8;accelerate,0.5;addx,-SCREEN_WIDTH);
		OffCommand=cmd(stoptweening;accelerate,0.5;addx,-SCREEN_WIDTH*1.5);
	};
	LoadActor("usb glow")..{
		InitCommand=cmd(x,SCREEN_CENTER_X-220;y,SCREEN_CENTER_Y-80;diffusealpha,0;);
		OnCommand=cmd(sleep,1.5;diffusealpha,1;linear,0.8;zoomx,3;zoomy,3;diffusealpha,0);
		OffCommand=cmd(stoptweening;accelerate,0.5;addx,-SCREEN_WIDTH*1.5);
	};

	Def.ActorFrame{
		OffCommand=cmd(stoptweening;accelerate,0.5;addx,-SCREEN_WIDTH*1.5);
		LoadActor(THEME:GetPathB("","_overlay/cardstats"))..{
			InitCommand=cmd(x,SCREEN_LEFT+120;y,SCREEN_CENTER_Y+155;croptop,.5;cropbottom,.5;);
			OnCommand=cmd(sleep,5.15;accelerate,.15;croptop,.25;cropbottom,.25;decelerate,.2;croptop,0;cropbottom,0;sleep,4.7;linear,.5;diffusealpha,0;);
		};
		LoadActor(THEME:GetPathB("","_overlay/p1card"))..{
			InitCommand=cmd(x,SCREEN_LEFT+60;y,SCREEN_CENTER_Y+165;diffusealpha,0;);
			OnCommand=cmd(sleep,5.5;linear,.3;diffusealpha,.6;sleep,4.4;linear,.5;diffusealpha,0;);
		};
		-- horiz line x2
		LoadFont("_r bold 30px")..{
			Text="Player Name";
			InitCommand=cmd(x,SCREEN_LEFT+120;y,SCREEN_CENTER_Y+87;diffusetopedge,color("#fff000");diffusebottomedge,color("#ffa500");shadowlength,2;horizalign,center;zoom,.8;diffusealpha,0;);
			OnCommand=cmd(sleep,5.4;linear,.2;diffusealpha,1;sleep,4.4;linear,.5;diffusealpha,0;);
		};
		LoadFont("_v profile")..{
			Text="Number of\nplayed songs";
			InitCommand=cmd(x,SCREEN_LEFT+148;y,SCREEN_CENTER_Y+162;shadowlength,2;horizalign,center;zoom,.8;diffusealpha,0;);
			OnCommand=cmd(sleep,5.65;linear,.2;diffusealpha,1;sleep,4.2;linear,.5;diffusealpha,0;);
		};

		LoadActor(THEME:GetPathB("","_overlay/achpane"))..{
			InitCommand=cmd(x,SCREEN_LEFT+242;y,SCREEN_CENTER_Y+155;addx,-54;cropleft,1;);
			OnCommand=cmd(sleep,4.7+.7;decelerate,.3;addx,54;cropleft,0;sleep,3.4;accelerate,.3;addx,-54;cropleft,1;);
		};
		Def.ActorFrame{
			Name="StarIcons";
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*0;horizalign,center;animate,0;zoom,0;);
				OnCommand=cmd(sleep,5.35+.6;playcommand,"Update");
				UpdateCommand=cmd(setstate,4;bounceend,0.4;zoom,.55;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*0;horizalign,center;animate,0;diffusealpha,0;);
				OnCommand=cmd(sleep,5.35+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,5;zoom,.55;sleep,.9;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*0;horizalign,center;animate,0;diffusealpha,0;);
				OnCommand=cmd(sleep,5.35+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,6;zoom,.55;sleep,1.55;linear,.3;diffusealpha,1;sleep,.4;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*0;horizalign,center;animate,0;diffusealpha,0;);
				OnCommand=cmd(sleep,5.35+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,7;zoom,.55;sleep,2.25;linear,.3;diffusealpha,1;sleep,.4;linear,.3;diffusealpha,0);
			};
		};
		Def.ActorFrame{
			Name="ThreeIcons";
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*1;horizalign,center;animate,0;zoom,0;);
				OnCommand=cmd(sleep,5.40+.6;playcommand,"Update");
				UpdateCommand=cmd(setstate,8;bounceend,0.4;zoom,.55;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*1;horizalign,center;animate,0;diffusealpha,0;);
				OnCommand=cmd(sleep,5.40+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,9;zoom,.55;sleep,.9;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*1;horizalign,center;animate,0;diffusealpha,0;);
				OnCommand=cmd(sleep,5.40+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,10;zoom,.55;sleep,1.55;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*1;horizalign,center;animate,0;diffusealpha,0;);
				OnCommand=cmd(sleep,5.40+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,11;zoom,.55;sleep,2.25;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
		};
		Def.ActorFrame{
			Name="ArrowIcons";
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*2;horizalign,center;animate,0;zoom,0;);
				OnCommand=cmd(sleep,5.45+.6;playcommand,"Update");
				UpdateCommand=cmd(setstate,0;bounceend,0.4;zoom,.55;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*2;horizalign,center;animate,0;diffusealpha,0);
				OnCommand=cmd(sleep,5.45+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,1;zoom,.55;sleep,.9;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*2;horizalign,center;animate,0;diffusealpha,0);
				OnCommand=cmd(sleep,5.45+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,2;zoom,.55;sleep,1.55;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*2;horizalign,center;animate,0;diffusealpha,0);
				OnCommand=cmd(sleep,5.45+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,3;zoom,.55;sleep,2.25;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
		};
		Def.ActorFrame{
			Name="PlusIcons";
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*3;horizalign,center;animate,0;zoom,0;);
				OnCommand=cmd(sleep,5.5+.6;playcommand,"Update");
				UpdateCommand=cmd(setstate,12;bounceend,0.4;zoom,.55;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*3;horizalign,center;animate,0;diffusealpha,0);
				OnCommand=cmd(sleep,5.5+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,13;zoom,.55;sleep,.9;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*3;horizalign,center;animate,0;diffusealpha,0);
				OnCommand=cmd(sleep,5.5+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,14;zoom,.55;sleep,1.55;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
			LoadActor(THEME:GetPathB("","_overlay/awards"))..{
				InitCommand=cmd(x,SCREEN_LEFT+238;y,SCREEN_CENTER_Y+103+34*3;horizalign,center;animate,0;diffusealpha,0);
				OnCommand=cmd(sleep,5.5+.5;playcommand,"Update");
				UpdateCommand=cmd(setstate,15;zoom,.55;sleep,2.25;linear,.3;diffusealpha,1;sleep,.3;linear,.3;diffusealpha,0);
			};
		};
	};
	LoadActor(THEME:GetPathB("ScreenAttract","overlay"));
};