return Def.ActorFrame{
	LoadActor("_triangle")..{
		--effectdelay,.6;
		InitCommand=cmd(blend,Blend.Add;x,-38;diffuseblink;effectcolor1,color("0.6,0.6,0.6,1");effectperiod,0.4;effectoffset,0.2;effectclock,"beat");
		ExitSelectedP1Command=cmd(stoptweening;linear,.15;rotationz,-90);
		ExitUnselectedP1Command=cmd(stoptweening;linear,.15;rotationz,0);
	};
	LoadActor("_triangle")..{
		--effectdelay,.6;
		InitCommand=cmd(blend,Blend.Add;x,38;diffuseblink;effectcolor1,color("0.6,0.6,0.6,1");effectperiod,0.4;effectoffset,0.2;effectclock,"beat");
		ExitSelectedP2Command=cmd(stoptweening;linear,.15;rotationz,90);
		ExitUnselectedP2Command=cmd(stoptweening;linear,.15;rotationz,0);
	};
	LoadActor("moreexit")..{
		InitCommand=cmd(y,-19;croptop,.57;cropbottom,.1);
		GainFocusCommand=cmd(stoptweening;linear,.15;y,-16;croptop,.57;cropbottom,.1);
		LoseFocusCommand=cmd(stoptweening;linear,.15;y,16;croptop,.07;cropbottom,.6);
	};

	Def.ActorFrame{
		InitCommand=cmd(x,-228+40;);
		BeginCommand=cmd(visible,GAMESTATE:IsPlayerEnabled(PLAYER_1));
		LoadActor("1")..{
			InitCommand=cmd(y,42;diffusealpha,0);
			ExitSelectedP1Command=cmd(stoptweening;decelerate,.2;y,52;diffusealpha,1);
			ExitUnselectedP1Command=cmd(stoptweening;accelerate,.2;y,42;diffusealpha,0);
			OffCommand=cmd(stoptweening;accelerate,.1;y,42;diffusealpha,0);
		};

		LoadActor("_ready")..{
			InitCommand=cmd(y,51;zoom,0);
			ExitSelectedP1Command=cmd(stoptweening;zoom,0;bounceend,.2;zoom,1);
			ExitUnselectedP1Command=cmd(stoptweening;bouncebegin,.2;zoom,0);
			OffCommand=cmd(stoptweening;bouncebegin,.1;zoom,0);
		};
		LoadActor("_textglow")..{
			InitCommand=cmd(y,51;diffusealpha,0);
			ExitSelectedP1Command=cmd(stoptweening;sleep,.1;diffusealpha,1;cropleft,-0.3;cropright,1;faderight,.1;fadeleft,.1;sleep,0.3;linear,1;cropleft,1;cropright,-0.3);
			ExitUnselectedP1Command=cmd(finishtweening;diffusealpha,0);
			OffCommand=cmd(stoptweening;linear,.1;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("","blueflare"))..{
			InitCommand=cmd(y,52;diffusealpha,0;zoomx,5;blend,Blend.Add);
			ExitSelectedP1Command=cmd(stoptweening;zoomy,3;linear,.1;diffusealpha,1;decelerate,.3;zoomy,0;diffusealpha,0);
			ExitUnselectedP1Command=cmd(stoptweening;diffusealpha,0);
			OffCommand=cmd(stoptweening;linear,.3;diffusealpha,0);
		};

		LoadActor("2")..{
			InitCommand=cmd(y,62;diffusealpha,0);
			ExitSelectedP1Command=cmd(stoptweening;decelerate,.2;y,52;diffusealpha,1);
			ExitUnselectedP1Command=cmd(stoptweening;accelerate,.2;y,62;diffusealpha,0);
			OffCommand=cmd(stoptweening;accelerate,.1;y,62;diffusealpha,0);
		};
	};
	Def.ActorFrame{
		InitCommand=cmd(x,228-40;);
		BeginCommand=cmd(visible,GAMESTATE:IsPlayerEnabled(PLAYER_2));
		LoadActor("3")..{
			InitCommand=cmd(y,42;diffusealpha,0);
			ExitSelectedP2Command=cmd(stoptweening;decelerate,.2;y,52;diffusealpha,1);
			ExitUnselectedP2Command=cmd(stoptweening;accelerate,.2;y,42;diffusealpha,0);
			OffCommand=cmd(stoptweening;accelerate,.1;y,42;diffusealpha,0);
		};

		LoadActor("_ready")..{
			InitCommand=cmd(y,51;zoom,0);
			ExitSelectedP2Command=cmd(stoptweening;zoom,0;bounceend,.2;zoom,1);
			ExitUnselectedP2Command=cmd(stoptweening;bouncebegin,.2;zoom,0);
			OffCommand=cmd(stoptweening;bouncebegin,.1;zoom,0);
		};
		LoadActor("_textglow")..{
			InitCommand=cmd(y,51;diffusealpha,0);
			ExitSelectedP2Command=cmd(stoptweening;sleep,.1;diffusealpha,1;cropleft,-0.3;cropright,1;faderight,.1;fadeleft,.1;sleep,0.3;linear,1;cropleft,1;cropright,-0.3);
			ExitUnselectedP2Command=cmd(finishtweening;diffusealpha,0);
			OffCommand=cmd(stoptweening;linear,.1;diffusealpha,0);
		};
		LoadActor(THEME:GetPathG("","blueflare"))..{
			InitCommand=cmd(y,52;diffusealpha,0;zoomx,5;blend,Blend.Add);
			ExitSelectedP2Command=cmd(stoptweening;zoomy,3;linear,.1;diffusealpha,1;decelerate,.3;zoomy,0;diffusealpha,0);
			ExitUnselectedP2Command=cmd(stoptweening;diffusealpha,0);
			OffCommand=cmd(stoptweening;linear,.3;diffusealpha,0);
		};

		LoadActor("4")..{
			InitCommand=cmd(y,62;diffusealpha,0);
			ExitSelectedP2Command=cmd(stoptweening;decelerate,.2;y,52;diffusealpha,1);
			ExitUnselectedP2Command=cmd(stoptweening;accelerate,.2;y,62;diffusealpha,0);
			OffCommand=cmd(stoptweening;accelerate,.1;y,62;diffusealpha,0);
		};
	};
};