return Def.ActorFrame{
	Def.Quad{
		InitCommand=cmd(Center;FullScreen;draworder,100;diffuse,color("0,0,0,0"););
		OnCommand=cmd(linear,.1;diffuse,color("1,1,1,1"););
	};
	Def.Quad{
		InitCommand=cmd(Center;FullScreen;draworder,152;diffuse,color("0,0,0,0"););
		OnCommand=cmd(sleep,2;linear,.4;diffuse,color("#000000"));
	};
	Def.Quad{
		InitCommand=cmd(Center;FullScreen;draworder,150;diffuse,color("0,0,0,0"););
		OnCommand=cmd(sleep,1;linear,.6;diffuse,color("0,0,0,0"););
	};
	LoadActor("_itg3")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-2;draworder,117;diffusealpha,0;zoomto,SCREEN_WIDTH,SCREEN_WIDTH/6.4;);
		OnCommand=cmd(linear,1.2;diffusealpha,1;);
	};
	LoadActor("blueflare")..{
		InitCommand=cmd(Center;blend,Blend.Add;draworder,115;zoomx,15;zoomtoheight,SCREEN_HEIGHT+SCREEN_HEIGHT/4;);
		OnCommand=cmd(decelerate,1.1;zoomtoheight,0;diffusealpha,.2;);
	};
	LoadActor("fire")..{
		InitCommand=cmd(Center;blend,Blend.Add;zoomto,SCREEN_WIDTH,SCREEN_WIDTH/6.4;draworder,117);
		OnCommand=cmd(sleep,.8;linear,.5;diffusealpha,0;);
	};
	LoadActor("fire")..{
		InitCommand=cmd(Center;blend,Blend.Add;zoomto,SCREEN_WIDTH,SCREEN_WIDTH/6.4;draworder,117);
		OnCommand=cmd(sleep,.8;linear,.5;diffusealpha,0;);
	};
	LoadActor("top")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-SCREEN_HEIGHT;draworder,110;zoomtowidth,SCREEN_WIDTH;);
		OnCommand=cmd(decelerate,.25;y,SCREEN_CENTER_Y-SCREEN_HEIGHT/4;);
	};
	LoadActor("bottom")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+SCREEN_HEIGHT;draworder,110;zoomtowidth,SCREEN_WIDTH);
		OnCommand=cmd(decelerate,.25;y,SCREEN_CENTER_Y+SCREEN_HEIGHT/4;);
	};
	LoadActor("blueflare")..{
		InitCommand=cmd(Center;blend,Blend.Add;draworder,115;diffusealpha,.6;zoomx,15;zoomtoheight,SCREEN_HEIGHT+SCREEN_HEIGHT/4;);
		OnCommand=cmd(decelerate,.7;zoomtoheight,.2;diffusealpha,0;);
	};
};